services:
  postgres:
    image: postgres:16
    container_name: farmaexpres_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/farmaexpres_users
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: mi_clave_secreta_larga
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  inventory-service:
    build: ./inventory-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/farmaexpres_inventory
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: mi_clave_secreta_larga
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-gateway:
    build: ./api-gateway
    depends_on:
      - auth-service
      - inventory-service
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5